[package]
name = "zenseapi"
version = "0.0.1"
authors = ["Takehiro Matsushima <takehiro.dreamizm@gmail.com>"]
edition = "2018"
publish = false

[dependencies]
libc = "0.2"
zenseapi-sys = { path = "../zenseapi-sys" }